config/routes.rb
MealyzerStudy::Application.routes.draw do

  root 'home#index'
  resources :meals
  resources :match_answers
  resources :users

  get 'admin', to: 'admin#index'
  delete 'admin', to: 'admin#exit'

  get 'finish', to: 'users#post_test', as: :post_test
  put 'finish', to: 'users#update_survey', as: :finish
  get 'completed', to: 'users#completed', as: :completed

  resource :match_answer_group

  match 'process', to: 'process#create', via: :post

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  %w(food_locations food_options food_nutrition food_components).each {|column| serialize column, JSON}

  GROUPS = ["Protein", "Fat", "Carbohydrate", "Fiber"]
  LC_GROUPS = GROUPS.map(&:downcase)
  VOWELS = %w(a e i o u)
  GRP_ABBRVS = ActiveSupport::OrderedHash[*GROUPS.sort.map{ |g| [g, (g.split(//) - VOWELS)[0,2].join] }.flatten]

  has_attached_file :photo, :styles => { :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  scope :enabled, -> { where(disabled: false) }
  scope :by_enabled_and_name, -> { order(:disabled, :name) }

  def self.random
    Meal.enabled.first(:offset => rand(Meal.enabled.count))
  end

  # Returns an array of pairs of form [meal_id, component name] for all Meals in system.
  def self.all_tests
    @all_tests ||= build_all_tests
  end

  def sample_component_name
    food_components.keys.sample
  end

  def items_for_component(name)
    food_components[name]
  end

  def nutrients_for_ingredient(component_name, ingredient)
    food_nutrition.try(:[], component_name).try(:[], ingredient) || []
  end

  def location_for_component(name)
    food_locations.try(:[], name)
  end

  def component_names
    food_components.try(:keys) || []
  end

  private

  def self.build_all_tests
    all_tests = []
    Meal.enabled.all.each do |meal|
      meal.food_components.each do |k,v|
        all_tests << [meal.id, k]
      end
    end
    return all_tests
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.by_enabled_and_name
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  # Currently only used for updating food locations
  def update
    @meal = Meal.find(params[:id])

    # Assign and save with bang since validation should never fail.
    @meal.assign_attributes(meal_params)
    @meal.save!

    # If we get this far, we just need to return a 200 status code. JS does rest.
    render nothing: true
  end

  private

  def meal_params
    # Get list of permitted hash keys
    location_hash = Hash[*@meal.component_names.map{ |c| [c, [:x, :y, :width, :height]] }.flatten(1)]
    params.require(:meal).permit(food_locations: location_hash)
  end
end

app/helpers/meals_helper.rb
module MealsHelper

  def meal_photo(meal)
    content_tag(:div, class: "meal-photo") do
      image_tag(meal.photo, id: "photo") << meal_photo_credit(meal)
    end
  end

  def meal_photo_credit(meal)
    if meal.photo_credit.blank?
      ""
    else
      linked = meal.photo_credit.gsub(%r{(https?://[^ ]+)}){ link_to("Link", $1) }.html_safe
      content_tag(:div, linked, class: "credit")
    end
  end

end

app/views/meals/edit.html.erb
<div class="meals">
  <h1><%= @meal.name %></h1>

  <h3>Components</h3>
  <% if @meal.food_components.blank? %>
    None
  <% else %>
    <ul>
      <% @meal.food_components.each do |component_name, ingredients| %>
        <li>
          <strong><%= component_name %></strong>
          <ul>
            <% ingredients.each do |ingredient| %>
              <li><%= ingredient %> (<%= @meal.nutrients_for_ingredient(component_name, ingredient).join(', ') %>)</li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  <% end %>


  <h3>Locations</h3>
  <div class="instructions">
    <p>Draw a rectangle around the different food groups using your mouse.</p>
    <p>For the "comment", enter the component name. Spelling must match exactly.</p>
  </div>
  <%= image_tag @meal.photo, id: "food", class: "meal-photo annotatable", data: {id: @meal.id } %>
  <div class="row">
    <div class="col-md-4">
      <button class="btn btn-primary">Save</button>
    </div>
  </div>
</div>


<%= javascript_doc_ready do %>
  new Mealyzer.Views.FoodLocationsView({
    el: '.meals',
    meal_id: <%= @meal.id%>,
    component_names: <%=json @meal.component_names %>,
    locations: <%=json @meal.food_locations %>
  });
<% end %>

app/views/meals/index.html.erb
<div class="meals">
  <h1>Meals</h1>
  <table>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Components</th>
      </tr>
    <% @meals.each do |meal| %>
      <tr class="<%= meal.disabled? ? "disabled" : "" %>">
        <td><%= link_to(image_tag(meal.photo(:thumb)), edit_meal_path(meal)) %></td>
        <td><%= link_to(meal.name, edit_meal_path(meal)) %></td>
        <td><%= meal.component_names.join(", ") %></td>
      </tr>
    <% end %>
  </table>
</div>